name: "arbtr_app"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    env_file:
      - .env
    volumes:
      - ./user-service:/app

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    env_file:
      - .env
    volumes:
      - ./order-service:/app

  shared-service:
    build:
      context: ./shared-service
      dockerfile: Dockerfile.dev
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    env_file:
      - .env
    volumes:
      - ./shared-service:/app
