services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_LOG_LEVEL=warn
    ports:
      - "3000:3000"
    networks:
      - monitoring
      - app_shared_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    expose:
      - "9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
      - app_shared_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    logging:
      options:
        max-size: "10m"
        max-file: "3"


  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    container_name: node-exporter
    expose:
      - "9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro
    networks:
      - monitoring
      - app_shared_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  monitoring:
    driver: bridge
  app_shared_network:
    external: true