name: golang-prod

x-micro-service: &micro-service
  restart: unless-stopped
  env_file:
    - .env
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  agency-service:
    <<: *micro-service
    image: agency-service:1.0.0
    build:
      context: .
      dockerfile: agency-service/Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    networks:
      app_shared_network:
        aliases:
          - agency-service-golang
    expose:
      - "${AGENCY_SERVICE_PORT}"

  user-service:
    <<: *micro-service
    image: user-service:1.0.0
    build:
      context: .
      dockerfile: user-service/Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    networks:
      app_shared_network:
        aliases:
          - user-service-golang
    expose:
      - "${USER_SERVICE_PORT}"

  card-service:
    <<: *micro-service
    image: card-service:1.0.0
    build:
      context: .
      dockerfile: card-service/Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    networks:
      app_shared_network:
        aliases:
          - card-service-golang
    expose:
      - "${CARD_SERVICE_PORT}"

networks:
  app_shared_network:
    external: true