name: golang-dev

x-micro-service: &micro-service
  restart: always
  env_file:
    - .env
  volumes:
    - .:/app
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  user-service:
    <<: *micro-service
    image: user-service:0.0.1-dev
    build:
      context: .
      dockerfile: user-service/Dockerfile.dev
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    networks:
      app_shared_network:
        aliases:
          - user-service-golang
    expose:
      - "${USER_SERVICE_PORT}"

  order-service:
    <<: *micro-service
    image: order-service:0.0.1-dev
    build:
      context: .
      dockerfile: order-service/Dockerfile.dev
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    networks:
      app_shared_network:
        aliases:
          - order-service-golang
    expose:
      - "${ORDER_SERVICE_PORT}"

  shared-service:
    <<: *micro-service
    image: shared-service:0.0.1-dev
    build:
      context: .
      dockerfile: shared-service/Dockerfile.dev
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    networks:
      app_shared_network:
        aliases:
          - shared-service-golang
    expose:
      - "${SHARED_SERVICE_PORT}"

networks:
  app_shared_network:
    external: true