basePath: /api/temp-service
info:
  contact: {}
  title: Temp service
  version: "1.0"
paths:
  /v1/call-user-service-with-grpc:
    get:
      parameters:
      - default: hi
        description: message
        in: query
        name: message
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Call user-service via gRPC
      tags:
      - Temp
  /v1/kafka-message:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Handle kafka message
      tags:
      - Temp
  /v1/redis-cache:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Handle redis cache and mongo db
      tags:
      - Temp
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
