services:
  kong:
    image: kong:latest
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"  # Admin API порт (HTTP)
    networks:
      - app-shared-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./kong.yml:/usr/local/kong/kong.yml

networks:
  app-shared-network:
    external: true