services:
  kong:
    image: kong:${KONG_VERSION}
    container_name: kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"  # HTTP
      - "8443:8443"  # HTTPS
      - "8001:8001"  # Admin API port (HTTP)
    networks:
      - app_shared_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./kong.yml:/usr/local/kong/kong.yml
      - ./kong.conf:/etc/kong/kong.conf
      - ./certs/localhost.pem:/etc/kong/ssl/localhost.pem
      - ./certs/localhost-key.pem:/etc/kong/ssl/localhost-key.pem

networks:
  app_shared_network:
    external: true