services:
  kong:
    image: kong:latest
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8443:8443"  # Default port
      - "8001:8001"  # Admin API порт (HTTP)
    networks:
      - app-shared-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./kong.yml:/usr/local/kong/kong.yml
      - ./kong.conf:/etc/kong/kong.conf
      - ./certs/localhost.pem:/etc/kong/ssl/localhost.pem
      - ./certs/localhost-key.pem:/etc/kong/ssl/localhost-key.pem

networks:
  app-shared-network:
    external: true