x-kafka-service: &kafka-service
  image: bitnami/kafka:latest
  restart: always
  networks:
    - kafka-network
    - app-shared-network
  depends_on:
    - zookeeper

x-kafka-env: &kafka-env
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  ALLOW_PLAINTEXT_LISTENER: yes
  KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    volumes:
      - ./logback.xml:/opt/bitnami/zookeeper/conf/logback.xml
      - zookeeper_data:/bitnami/zookeeper

  kafka1:
    <<: *kafka-service
    container_name: kafka1
    environment:
      <<: *kafka-env
      KAFKA_BROKER_ID: "1"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
    ports:
      - "9092:9092"
    volumes:
      - ./log4j.properties:/opt/bitnami/kafka/config/log4j.properties
      - kafka1_data:/bitnami/kafka

  kafka2:
    <<: *kafka-service
    container_name: kafka2
    environment:
      <<: *kafka-env
      KAFKA_BROKER_ID: "2"
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
    ports:
      - "9093:9093"
    volumes:
      - ./log4j.properties:/opt/bitnami/kafka/config/log4j.properties
      - kafka2_data:/bitnami/kafka

  kafka3:
    <<: *kafka-service
    container_name: kafka3
    environment:
      <<: *kafka-env
      KAFKA_BROKER_ID: "3"
      KAFKA_LISTENERS: PLAINTEXT://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
    ports:
      - "9094:9094"
    volumes:
      - ./log4j.properties:/opt/bitnami/kafka/config/log4j.properties
      - kafka3_data:/bitnami/kafka

networks:
  kafka-network:
    driver: bridge
  app-shared-network:
    external: true

volumes:
  zookeeper_data:
  kafka1_data:
  kafka2_data:
  kafka3_data: