ARG GOLANG_VERSION

FROM golang:${GOLANG_VERSION:-1.24}-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

ENV PATH="/go/bin:${PATH}"

COPY . .

WORKDIR /app/agency-service

RUN go mod tidy

CMD ["air"]