x-mongo-service: &mongo-service
  image: mongo:${MONGO_VERSION}
  command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
  restart: always
  expose:
    - "27017"
  networks:
    - app_shared_network
  environment:
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  mongo1:
    <<: *mongo-service
    container_name: mongo1
    volumes:
      - mongo1_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf:ro
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile:ro

  mongo2:
    <<: *mongo-service
    container_name: mongo2
    volumes:
      - mongo2_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf:ro
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile:ro

  mongo3:
    <<: *mongo-service
    container_name: mongo3
    volumes:
      - mongo3_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf:ro
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile:ro

  mongo-setup:
    image: mongo:${MONGO_VERSION}
    container_name: mongo-setup
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app_shared_network
    volumes:
      - ./setup.sh:/setup.sh
    entrypoint: [ "/setup.sh" ]
    depends_on:
      - mongo1
      - mongo2
      - mongo3

networks:
  app_shared_network:
    external: true

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: