x-mongo-service: &mongo-service
  image: mongo:${MONGO_VERSION}
  restart: always
  networks:
    - app_shared_network

x-mongo-command: &mongo-command
   bash -c '
     mkdir -p /etc/mongo &&
     cp /tmp/keyfile /etc/mongo/keyfile &&
     chown mongodb:mongodb /etc/mongo/keyfile &&
     chmod 400 /etc/mongo/keyfile &&
     mongod --replSet rs0 --keyFile /etc/mongo/keyfile --port 27017 --bind_ip_all
   '

services:
  mongo1:
    <<: *mongo-service
    container_name: mongo1
    volumes:
      - mongo1_data:/data/db
      - ./keyfile:/tmp/keyfile:ro
      - ./setup.sh:/setup.sh
    entrypoint: [ "/setup.sh" ]
    ports:
      - "27017:27017"

  mongo2:
    <<: *mongo-service
    container_name: mongo2
    command: *mongo-command
    volumes:
      - mongo2_data:/data/db
      - ./keyfile:/tmp/keyfile:ro

  mongo3:
    <<: *mongo-service
    container_name: mongo3
    command: *mongo-command
    volumes:
      - mongo3_data:/data/db
      - ./keyfile:/tmp/keyfile:ro

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

networks:
  app_shared_network:
    external: true